// src/components/Filters/SermonFilter.tsx
import * as React from "react";
import type { PreacherData, SeriesData, SermonData } from "@/lib/types";
import { useStore } from "@nanostores/react";
import {
  $series,
  $preacher,
  $from,
  $to,
  $sermonsSearchTerm,
} from "@/lib/nanostores";
import { DatePickerCustom } from "@/components/Filters/DatePickerCustom";
import { Combobox } from "@/components/Filters/Combobox";
import { StyledText } from "../StyledText";
import { Settings2, Undo2 } from "lucide-react";
import { Button } from "../ui/button";
import Search from "./Search";
import { useState } from "react";

// TODO: Consider converting to API endpoint rather than passing data?
interface SermonFilterProps {
  allSermonData: SermonData[];
  allSeriesData: SeriesData[];
  allPreachersData: PreacherData[];
}

const SermonFilter: React.FC<SermonFilterProps> = ({
  allSermonData,
  allSeriesData,
  allPreachersData,
}) => {
  const [isShowFilters, setIsShowFilters] = useState(false);

  const searchTerm = useStore($sermonsSearchTerm);
  const series = useStore($series);
  const preacher = useStore($preacher);
  const from = useStore($from);
  const to = useStore($to);

  const resetFilters = () => {
    $series.set(undefined);
    $preacher.set(undefined);
    $from.set(null);
    $to.set(null);
    $sermonsSearchTerm.set("");
    setIsShowFilters(false);
  };

  let titleText;

  if (searchTerm) {
    titleText = `Sermons matching ${searchTerm}`;
  } else if (series) {
    titleText = `Sermons from ${allSeriesData.find((i) => i.id === series)?.data.title}`;
  } else if (preacher) {
    titleText = `Sermons by ${allPreachersData.find((i) => i.id === preacher)?.data.name}`;
  } else if (to && from) {
    titleText = `Sermons between ${from.toString()} and ${to.toString()}`;
  } else if (from) {
    titleText = `Sermons after ${from.toString()}`;
  } else if (to) {
    titleText = `Sermons before ${to.toString()}`;
  } else {
    titleText = "All Sermons";
  }

  return (
    <div className="flex flex-col gap-4">
      <StyledText as="h2" variant="heading">
        {titleText}
      </StyledText>
      <div className="flex flex-col gap-4 md:flex-row">
        <Search className="bg-muted text-muted-foreground" type="sermons" />
        <div className="flex content-between justify-between self-end">
          <Button
            variant="link"
            onClick={() => setIsShowFilters(!isShowFilters)}
            className={isShowFilters ? "" : "text-muted-foreground"}
          >
            <Settings2 />
            {isShowFilters ? "Hide Filters" : "Show Filters"}
          </Button>
          {(series || preacher || from || to) && (
            <Button
              variant="link"
              className="flex w-fit cursor-pointer items-center gap-1 px-0 py-0"
              onClick={resetFilters}
            >
              Reset Filters
              <Undo2 />
            </Button>
          )}
        </div>
      </div>

      {isShowFilters && (
        <div className="flex flex-col gap-x-8 gap-y-4 lg:grid lg:grid-cols-2">
          <Combobox data={allSeriesData} type="series" />
          <Combobox data={allPreachersData} type="preacher" />
          <DatePickerCustom data={allSermonData} type="from" />
          <DatePickerCustom data={allSermonData} type="to" />
        </div>
      )}
    </div>
  );
};

export { SermonFilter };

// src/lib/components/SermonFilter/SermonFilter.svelte
<script lang="ts">
import type { CollectionEntry } from "astro:content";
import { type DateValue } from "@internationalized/date";
import { Undo2 } from "@lucide/svelte";
import Text from "$lib/components/Text.svelte";
import Button from "$lib/components/ui/button/button.svelte";
import { from, preacher, series, to } from "$lib/nanostores";
import type { PreacherData, SeriesData, SermonData } from "$lib/types";
import DatePicker from "./SermonFilterDatepicker.svelte";
import Select from "./SermonFilterSelect.svelte";

let {
  allSermonData,
  allSeriesData,
  allPreachersData,
}: {
  allSermonData: SermonData[];
  allSeriesData: SeriesData[];
  allPreachersData: PreacherData[];
} = $props();

const selectedSeries = $derived(
  allSeriesData.find((item) => item.id === $series),
);

const resetFilters = () => {
  series.set(undefined);
  preacher.set(undefined);
  from.set(undefined);
  to.set(undefined);
};
</script>

<Text as="h2" variant="heading">
  {selectedSeries
    ? `Sermons from ${selectedSeries?.data.title}`
    : "All Sermons"}
</Text>

{#if $series || $preacher || $from || $to}
  <Button
    variant="link"
    class="flex gap-1 items-center cursor-pointer w-fit px-0 py-0"
    onclick={() => resetFilters()}
  >
    Reset Filters
    <Undo2 />
  </Button>
{/if}

<div class="flex flex-col gap-2 md:grid md:grid-cols-2">
  <Select label="Series" bind:value={$series} data={allSeriesData} />
  <Select label="Preacher" bind:value={$preacher} data={allPreachersData} />
  <DatePicker label="From" bind:value={$from as DateValue} />
  <DatePicker label="From" bind:value={$to as DateValue} />
</div>
