// src/components/SubscribeForm.tsx
import * as React from "react";
import { useForm, useStore } from "@tanstack/react-form";
import { Button } from "./ui/button";
import { Field, FieldError, FieldGroup } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Toaster } from "./ui/sonner";
import { toast } from "sonner";
import * as z from "zod";

export const subscribeFormSchema = z.object({
  firstName: z.string().min(2, "First name must be at least 2 characters."),
  lastName: z.string().min(2, "Last name must be at least 2 characters."),
  email: z.email("Enter a valid email address."),
});

interface SubscribeFormProps {}

const SubscribeForm: React.FC<SubscribeFormProps> = ({}) => {
  const form = useForm({
    defaultValues: {
      firstName: "",
      lastName: "",
      email: "",
    },
    validators: {
      onSubmit: subscribeFormSchema,
    },
    onSubmit: async ({ value }) => {
      const response = await fetch(
        `${import.meta.env.DEV ? "http://localhost:4321" : import.meta.env.SITE}/api/subscribe`,
        {
          method: "POST",
          body: JSON.stringify(value),
        },
      );

      const { code, message } = await response.json();

      if (code === "BAD_REQUEST") {
        toast.error(message);
        return;
      }

      if (code === "CONFLICT") toast.info(message);
      if (code === "SUCCESS") toast.success(message);

      // TODO: Style Sonner
      // if (data.message === "") toast.info(data.message);

      // toast("You submitted the following values:", {
      //   description: (
      //     <pre className="bg-code text-code-foreground mt-2 w-[320px] overflow-x-auto rounded-md p-4">
      //       <code>{JSON.stringify(value, null, 2)}</code>
      //     </pre>
      //   ),
      //   position: "bottom-right",
      //   classNames: {
      //     content: "flex flex-col gap-2",
      //   },
      //   style: {
      //     "--border-radius": "calc(var(--radius)  + 4px)",
      //   } as React.CSSProperties,
      // });
      // console.log(post);

      form.reset();
    },
  });

  // const firstName = useStore(form.store, (state) => state.values.firstName);
  // const lastName = useStore(form.store, (state) => state.values.lastName);
  // const email = useStore(form.store, (state) => state.values.email);
  // const errors = useStore(form.store, (state) => state.errorMap);

  // const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
  //   e.preventDefault();
  //   const formData = new FormData(e.target as HTMLFormElement);
  //   const { data, error } = await actions.subscribe(formData);
  //   if (error) {
  //     return toast.error(error.message);
  //   }
  //   toast.success(data);
  // };

  return (
    <>
      <form
        id="subscribe-form"
        onSubmit={(e) => {
          e.preventDefault();
          form.handleSubmit();
        }}
      >
        <FieldGroup>
          <form.Field
            name="firstName"
            children={(field) => {
              const isInvalid =
                field.state.meta.isTouched && !field.state.meta.isValid;
              return (
                <Field data-invalid={isInvalid}>
                  {/*<FieldLabel htmlFor={field.name}>First Name</FieldLabel>*/}
                  <Input
                    id={field.name}
                    name={field.name}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    aria-invalid={isInvalid}
                    placeholder="First Name"
                    autoComplete="off"
                    className="bg-muted text-muted-foreground"
                  />
                  {isInvalid && <FieldError errors={field.state.meta.errors} />}
                </Field>
              );
            }}
          />
          <form.Field
            name="lastName"
            children={(field) => {
              const isInvalid =
                field.state.meta.isTouched && !field.state.meta.isValid;
              return (
                <Field data-invalid={isInvalid}>
                  {/*<FieldLabel htmlFor={field.name}>Last Name</FieldLabel>*/}
                  <Input
                    id={field.name}
                    name={field.name}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    aria-invalid={isInvalid}
                    placeholder="Last Name"
                    autoComplete="off"
                    className="bg-muted text-muted-foreground"
                  />
                  {isInvalid && <FieldError errors={field.state.meta.errors} />}
                </Field>
              );
            }}
          />
          <form.Field
            name="email"
            children={(field) => {
              const isInvalid =
                field.state.meta.isTouched && !field.state.meta.isValid;
              return (
                <Field data-invalid={isInvalid}>
                  {/*<FieldLabel htmlFor={field.name}>Email</FieldLabel>*/}
                  <Input
                    id={field.name}
                    name={field.name}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    aria-invalid={isInvalid}
                    placeholder="mail@example.com"
                    autoComplete="off"
                    className="bg-muted text-muted-foreground"
                  />
                  {isInvalid && <FieldError errors={field.state.meta.errors} />}
                </Field>
              );
            }}
          />
        </FieldGroup>
        <form.Subscribe
          selector={(state) => [state.canSubmit, state.isSubmitting]}
          children={([canSubmit, isSubmitting]) => (
            <Button type="submit" disabled={!canSubmit}>
              {isSubmitting ? "..." : "Subscribe"}
            </Button>
          )}
        />
      </form>
      <Toaster />
    </>
  );
};

export default SubscribeForm;

// src/lib/components/SubscribeForm/SubscribeForm.svelte
<script lang="ts">
import { actions } from "astro:actions";
import { Mail } from "@lucide/svelte";

import { toast } from "svelte-sonner";

import { type SuperValidated, superForm } from "sveltekit-superforms";
import { zod4Client } from "sveltekit-superforms/adapters";
import {
  type Message,
  type SubscribeValues,
  zSubscribeValues,
} from "$lib/components/SubscribeForm/schema";
import * as Card from "$lib/components/ui/card";
import * as Form from "$lib/components/ui/form";
import { Input } from "$lib/components/ui/input";
import * as InputGroup from "$lib/components/ui/input-group";
import { Toaster } from "$lib/components/ui/sonner";

let { sv }: { sv: SuperValidated<SubscribeValues, Message> } = $props();

const sf = superForm(sv, {
  validators: zod4Client(zSubscribeValues),
  onError: () => {
    toast.error(i18n());
  },
  onUpdated: ({ form: { message, valid } }) => {
    if (message)
      valid ? toast.success(i18n(message)) : toast.error(i18n(message));
  },
});
const { delayed, enhance, form, submitting } = sf;

function i18n(code?: Message) {
  if (code === "BAD_REQUEST")
    return "An error occurred. Please try again later.";
  if (code === "CONFLICT") return "You are already subscribed.";
  if (code === "SUCCESS") return "Successfully subscribed.";
  return "An error occurred. Please try again later.";
}
</script>

<Card.Root class="w-full py-0 bg-accent border-none shadow-none">
  <form
    method="POST"
    action={actions.submit}
    use:enhance
    novalidate
    class="flex flex-col gap-2"
  >
    <Card.Content class="gap-2 flex flex-col px-0">
      <Form.Field form={sf} name="firstName">
        <Form.Control>
          {#snippet children({ props })}
            <Input
              {...props}
              type="text"
              bind:value={$form.firstName}
              placeholder="First Name"
              class="bg-muted text-muted-foreground mb-0"
            />
          {/snippet}
        </Form.Control>
        <Form.FieldErrors class="text-red-300 *:py-1" />
      </Form.Field>
      <Form.Field form={sf} name="lastName">
        <Form.Control>
          {#snippet children({ props })}
            <Input
              {...props}
              type="text"
              bind:value={$form.lastName}
              placeholder="Last Name"
              class="bg-muted text-muted-foreground mb-0"
            />
          {/snippet}
        </Form.Control>
        <Form.FieldErrors class="text-red-300 *:pt-1" />
      </Form.Field>
      <Form.Field form={sf} name="email">
        <Form.Control>
          {#snippet children({ props })}
            <InputGroup.Root
              class="bg-muted text-muted-foreground mb-0 aria-invalid:border-red-400"
            >
              <InputGroup.Input
                {...props}
                type="email"
                bind:value={$form.email}
                placeholder="mail@site.com"
              />
              <InputGroup.Addon>
                <!-- <MailIcon /> -->
                <Mail />
              </InputGroup.Addon>
            </InputGroup.Root>
          {/snippet}
        </Form.Control>
        <Form.FieldErrors class="text-red-300 *:pt-1" />
      </Form.Field>
    </Card.Content>
    <Card.Footer class="px-0 w-full">
      <Form.Button
        disabled={$submitting}
        class="w-full"
        variant="footer-button"
        >{$delayed ? "Subscribing..." : "Subscribe"}</Form.Button
      >
    </Card.Footer>
  </form>
</Card.Root>
<Toaster />
