// src/lib/components/Sidebar.svelte
<script lang="ts">
import { Hamburger } from "svelte-hamburgers";
import NavMenu from "$lib/components/NavMenu.svelte";
import * as Drawer from "$lib/components/ui/drawer";

let open = $state(false);
</script>

<div class="z-100 lg:hidden pointer-events-auto">
  <Hamburger bind:open type="spin" --color="var(--muted-foreground)" --padding="0"/>
</div>

<Drawer.Root bind:open direction="right">
  <Drawer.Content class="data-[vaul-drawer-direction=right]:w-full data-[vaul-drawer-direction=right]:sm:max-w-full pt-24">
    <NavMenu class={"px-8 flex flex-col gap-2"} />
  </Drawer.Content>
</Drawer.Root>

// src/components/Sidebar.tsx
import * as React from "react";
import { Spin as Hamburger } from "hamburger-react";
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/components/ui/drawer";
import { Button } from "./ui/button";
import { NavMenu } from "./NavMenu.tsx";

interface SidebarProps {}

const Sidebar: React.FC<SidebarProps> = ({}) => {
  const [isOpen, setIsOpen] = React.useState(false);

  return (
    <>
      <Drawer open={isOpen} direction="right" onOpenChange={setIsOpen}>
        <DrawerTitle className="sr-only">Menu</DrawerTitle>
        <DrawerTrigger className="pointer-events-auto z-100 lg:hidden">
          <Hamburger
            toggled={isOpen}
            color="var(--muted-foreground)"
            // onToggle={setIsOpen}
          />
        </DrawerTrigger>
        <DrawerContent className="pt-24 data-[vaul-drawer-direction=right]:w-full data-[vaul-drawer-direction=right]:sm:max-w-full">
          <NavMenu />
        </DrawerContent>
      </Drawer>
    </>
  );
};

export { Sidebar };
