// src/lib/components/SermonCard/SermonCard.svelte
<script lang="ts">
import {format} from "date-fns"
import Text from "$lib/components/Text.svelte"
import * as Card from "$lib/components/ui/card"
import {type SermonData} from "$lib/types"

const {baseUrl, sermon}: {baseUrl: string, sermon: SermonData} = $props()
const {
  id,
  data: { title, date, scripture },
  series: {
    data: { imageSquare },
  },
  preacher: {
    data: { name },
  },
} = sermon;
</script>

<Card.Root class="py-0 border-none rounded-sm shadow-sm bg-muted">
  <Card.Content class="p-0 flex flex-row">
    <a href={`${baseUrl}${id}`} class="flex max-h-48 flex-row w-full">
      <img
        src={imageSquare}
        alt="series"
        class="h-full rounded-l-sm max-sm:flex-1/3"
      />
      <div class="xs:p-4 flex flex-2/3 flex-col justify-center p-2 sm:p-8">
        <Text as="h3" variant="subheading">{title}</Text>
        <Text as="span" variant="meta">
          {format(
            new Date(date.valueOf() + date.getTimezoneOffset() * 60 * 1000),
            "LLLL dd, yyyy",
          )}
          <br />
          {scripture}
          <br />
          {name}
        </Text>
      </div>
    </a>
  </Card.Content>
</Card.Root>

// src/components/SermonCards/SermonCard.tsx
import * as React from "react";
import { type SermonData } from "@/lib/types";
import { Card, CardContent } from "@/components/ui/card";
import { format } from "date-fns";
import { StyledText } from "../StyledText";

interface SermonCardProps {
  baseUrl: string;
  sermon: SermonData;
}

const SermonCard: React.FC<SermonCardProps> = ({ baseUrl, sermon }) => {
  const {
    id,
    data: { title, date, scripture },
    series: {
      data: { imageSquare },
    },
    preacher: {
      data: { name },
    },
  } = sermon;

  return (
    <Card className="bg-muted rounded-sm border-none py-0 shadow-sm">
      <CardContent className="flex flex-row p-0">
        <a href={`${baseUrl}${id}`} className="flex max-h-48 w-full flex-row">
          <img
            src={imageSquare}
            alt="series"
            className="h-full rounded-l-sm max-sm:flex-1/3"
          />
          <div className="xs:p-4 flex flex-2/3 flex-col justify-center p-2 sm:p-8">
            <StyledText as="h3" variant="subheading">
              {title}
            </StyledText>
            <StyledText as="span" variant="meta">
              {format(
                new Date(date.valueOf() + date.getTimezoneOffset() * 60 * 1000),
                "LLLL dd, yyyy",
              )}
              <br />
              {scripture}
              <br />
              {name}
            </StyledText>
          </div>
        </a>
      </CardContent>
    </Card>
  );
};

export { SermonCard };
